### ISSUE TITLE
error in require("TSlib") 

### ISSUE THREAD

**Issue by poppinjie** [AuTsing/touchsprite-extension#4]
发生异常: E:\����\ȫ�Զ�����ű�\Ǯ��_v1.0/TSLib.lua: bad binary format (not a binary chunk)
stack traceback:
	ocr.lua:1: in main chunk
	[C]: in function 'require'
	main.lua:1: in main chunk
	[C]: in ?

When I debug the main.lua file, I encounted the above problem. How to deal with it? Should I download the TSLib.lua file and put it in my project?

**Comment by AuTsing** [comment]
你现在尝试的是在PC运行调试，可是实际上TSLib只适用于手机

**Comment by AuTsing** [comment]
issue先关闭了，如有更多问题欢迎提交新的issue
