### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by truemogician** [AuTsing/touchsprite-extension#7]
环境：VSCode 1.62.0， TouchSprite Extension 1.10.2, Lua 2.4.7
设备：雷电模拟器 4.0.67
问题描述：模拟器通过桥接模式连接到局域网内，可以ping通，TouchSprite Extension也可以搜索到并连接；AccessKey已正确配置；模拟器上触动服务已经启动；运行工程、运行脚本、上传文件等指令均会报Error: read ECONNRESET，重启VSCode或者模拟器也一样 ；但同样的项目，使用TS Studio的时候这些功能都正常运行。

**Comment by AuTsing** [comment]
检查是否开启了代理软件，尝试关闭后再运行，如果有真机，测试真机是否正常

**Comment by truemogician** [comment]
代理确实开了，但退出之后设备会连接失败，报错Error: connect ECONNREFUSED+我的代理地址，但此时系统代理已经关闭，不知道TouchSprite Extension是使用了哪里的代理设置

**Comment by AuTsing** [comment]
确认退出所有代理软件之后，重启vscode，再进行连接。如果你关闭了所有代理设置理论上不会读取到你的代理地址才对。

**Comment by AuTsing** [comment]
插件本身不会调用代理，如果显示代理地址则说明你配置了代理。

**Comment by truemogician** [comment]
啊，我找到了，是我之前设置了VSCode的默认代理，插件应该用的这个

**Comment by truemogician** [comment]
感谢如此迅速的回复
